input:
    path: input.csv
modules:
    interactome:
        mentha2pdb:
            database_date: 2025-04-28
            database_path: /data/databases/mentha-20250428
            AF_Huri_path:  /data/databases/AF_Huri_HuMAP/summary/HuRI.csv
            AF_HuMAP_path: /data/databases/AF_Huri_HuMAP/summary/humap.csv
            AF_Huri_HuMAP_path: /data/databases/AF_Huri_HuMAP
        hpc_atlas:
            database_path: /data/databases/hpc_atlas/HPC-Atlas_gene.txt
    structure_selection:
        alphafold:
            dssp_exec: /usr/local/dssp-4.4/bin/mkdssp
        pdbminer:
            pdbminer_env: . /usr/local/envs/PDBminer/bin/activate
        procheck:
            procheck_env: export prodir=/usr/local/procheck && export PATH=$PATH:$prodir
    mutations_classifier:
        demask:
            source: /usr/local/envs/demask/demask_env/bin/activate 
            database_path: /data/databases/uniref90demask/uniref90demask
            blastp_path: /usr/local/blast_plus-2.13.0/bin/blastp
        alphamissense:
            database_path: /data/databases/alphamissense/AlphaMissense_aa_substitutions.tsv.gz 
    mutations_aggregation:
        cancermuts:
            source: /usr/local/envs/cancermuts/bin/activate
            Cosmic_database_path: /data/databases/cosmic-v96/CosmicMutantExport.tsv
            saturation: true
            ELM_connections_per_run: 1
            folder_name: /data/raw_data/computational_data/cancermuts_data/
        mutlist:
            source: . /usr/local/envs/cancermuts/bin/activate
        mutatex:
            repository: /data/raw_data/computational_data/mutatex_data/
    rasp:
        conda_activation: /usr/local/miniconda3/bin/activate
        rasp_conda_env: /usr/local/envs/RaSP_workflow
        output_path_folder: /data/raw_data/computational_data/rasp_data/
        folder_name: rasp
    rosetta_relax:
        rosetta_env: /usr/local/envs/rosettaddgprediction/bin/activate
        rosetta_module: /usr/local/rosetta-2022.11/
        rosetta_folder:  /data/raw_data/computational_data/rosetta_data/
        rosetta_template: /data/raw_data/computational_data/rosetta_data/mavisp_templates/stability/ref2015_cartesian2020
    efoldmine:
        environment: set +eu && . /usr/local/envs/efoldmine/bin/activate && set -eu
