# Path to the DSSP executable
dssp_exec: "/usr/local/dssp-4.4/bin/mkdssp"

# pLDDT score cutoff
plddt_cutoff: 70

# UniProt IDs of the proteins of interest
uniprot_ids:

  # 
  O94817:
    # Name of the directory (created in the current
    # working directory) where to save the data
    dir_name: "pole"
    # Version of the AlphaFoldDB structure, use "latest" or int of version
    version: "latest"
